### ISSUE TITLE
What git-flow do we want to use?

### ISSUE THREAD

**Issue by raleighleslie** [codeablehq/expertstatsplugin#13]
Just committed to master the readme and some screenshots...

So I wanted to bring up how we should do this looking ahead with feature branches and pull requests ect... 

Just creating the issue for now I assume @vimes1984 may have input as I really don't know what's best! Thanks - Raleigh :D

**Comment by vimes1984** [comment]
We should now use typical fork and pull requests and any admin on the repo will then merge in after testing!
