### ISSUE TITLE
cant view transaction before 2014

### ISSUE THREAD

**Issue by kotfarepra** [codeablehq/expertstatsplugin#24]
As one of the oldest on ...... in my time .... they dont make good pasta like they did back then ..... 

.... .

There are no transactions before 2014 . Ive been on codeable since January 2013 and i have done tasks that year but even tried 3-4 times re-fetching the data the oldest i see is January 2014 .

Regards

**Comment by vimes1984** [comment]
If I'm not mistaken the API was very very different back then and there isn't much backwards compatibility .
