### ISSUE TITLE
Another stat to track?

### ISSUE THREAD

**Issue by nathanello** [codeablehq/expertstatsplugin#26]
Hey guys, first off I just want to say that I'm really loving the plugin, there's so much wonderful information here at my fingertips now, I feel like a kid on Christmas!

One stat that I track personally is my average task size month-over-month as my goal as a freelancer is to work on less tasks that are ultimately worth more money... Perhaps that could be overlaid on the "tasks per month" bar graph to chart total # of tasks VS average task size.

Anyways, just thinking out loud here...

**Comment by 11digitlabs** [comment]
I think we are good with the number of stats we have. If really necessary we'll discuss again
