### ISSUE TITLE
Make this plugin public?

### ISSUE THREAD

**Issue by nathanello** [codeablehq/expertstatsplugin#27]
Hey guys, why not release the plugin publicly and if someone doesn't have a user/pass for Codeable you could either link them to either the apply to become a developer page OR create a new client account page? 

This could potentially be expanded into allowing clients to install this plugin on their site and pull a completely different dashboard with their own stats into their own WP site and allow them to post a new project right from their dashboard. Maybe it would showcase the developers they've worked with in the past and you could tie Referoo into this and end up making some $ from your plugin? 

Just thinking out loud here again... Will stop spamming this repo now :)

**Comment by vimes1984** [comment]
OK it's done!!!

**Comment by jin0x** [comment]
Hey @vimes1984 I am in too!!! Consider @spyrosvl and @11digitlabs opinions as mine also ;)
