### ISSUE TITLE
Chart downloads

### ISSUE THREAD

**Issue by nathanello** [codeablehq/expertstatsplugin#30]
Hey guys, I'd love to be able to download these charts to use in my blog... Specifically the "monthly money chart" + "Amounts Range" + "Tasks per Month" charts.

And by this I mean to simply download a jpg of the chart to quickly add to my blog.

**Comment by spyrosvl** [comment]
@nathanello give it a spin mate and let us know if this is good enough.

Browser compatibility here: http://www.highcharts.com/docs/export-module/client-side-export

**Comment by 11digitlabs** [comment]
Closed and merged in master
