### ISSUE TITLE
Preferred Stats VS Non-Preferred

### ISSUE THREAD

**Issue by nathanello** [codeablehq/expertstatsplugin#31]
I just clicked into one of my clients and noticed you're able to track which tasks came in as preferred and which didn't. 

I think it would be really cool to have a little breakdown that shows total revenue generated by preferred tasks VS non-preferred tasks. 

Personally I'd like to share my #'s with the rest of the experts on Codeable to show them just how important these preferred tasks are and how easy it is to get them.

**Comment by spyrosvl** [comment]
@nathanello Please give it a try and let us know if this is something you had in mind :)

**Comment by 11digitlabs** [comment]
Yeah, looks good

**Comment by 11digitlabs** [comment]
Closed and merged in master
