### ISSUE TITLE
Revenue Tracked By Task Type

### ISSUE THREAD

**Issue by nathanello** [codeablehq/expertstatsplugin#32]
Hey Guys,

Also noticed we're able to drill down and see task type; "theme, plugin, project, subtask, install, etc" and I thought it might be cool to have a stat to track average task revenue based on task type? 

Might give us some sort of indication where our time is best spent?

**Comment by vimes1984** [comment]
@nathanello can you please test this and if it's good I'll close the issue.

**Comment by 11digitlabs** [comment]
On my end seems to be working fine

**Comment by 11digitlabs** [comment]
Closed and merged in master
