### ISSUE TITLE
Tasks per month/day legend

### ISSUE THREAD

**Issue by spyrosvl** [codeablehq/expertstatsplugin#34]
There is no use of the "Tasks" legend on the Tasks per month/day chart. It should be removed.

**Comment by 11digitlabs** [comment]
Agreed? Shall we put it to sleep?

**Comment by spyrosvl** [comment]
@11digitlabs I think we should leave it there, cause I would like to see average tasks per month or day. So it will be a horizontal line there (on the chart) and the info on the box above. What do you think?

**Comment by spyrosvl** [comment]
I mean, I would liek to add the above info, so the tasks legened will make sense after this.
