### ISSUE TITLE
Last login date not correct

### ISSUE THREAD

**Issue by 11digitlabs** [codeablehq/expertstatsplugin#35]
Seems like tha last login date of the clients is not updated, if there are no new tasks for that client.
If we need to update this date, then we have to go through all the clients and get the last login date.

It might take a while :)

**Comment by spyrosvl** [comment]
Indeed, however I am not sure if this data is vital. It is always nice though to spy on our former clients :)

**Comment by 11digitlabs** [comment]
Nope, it's not vital indeed. There is no need to implement everything we talk about here ;)
