### ISSUE TITLE
Add PERT weighted calculator

### ISSUE THREAD

**Issue by jonathanbossenger** [codeablehq/expertstatsplugin#37]
It might be a cool idea to add a simple PERT estimate calculator to the plugin, for estimating on tasks.

http://pastebin.com/EjxJMyC7

**Comment by jin0x** [comment]
I don't think that this is something that should be integrated to the project.
In UI terms that would break a lot the overall experience of the user which is focused on the statistics and it will also make the plugin's feel very bloat. 
There are so many good online converters out there that do the work. I use PERT Calculator as a workflow on my Alfred App (http://www.packal.org/workflow/pert-calculator) and that makes my calculations blazing fast and I have it always accessible.
Experts stats plugin is something I use at the end of my day or once a week to keep track on my progress where PERT Alfred workflow is something that I can use anytime.

This is just my humble opinion. Let's wait and see what other experts will say ;)

**Comment by wpbullet** [comment]
@jin0x if it was just a submenu item with a simple calculator that didn't really change the current experience what you still be against it?

The way I see it this is a useful tool that if added without affecting the current main dashboard and has no generally negative consequences, why not add it?

**Comment by vimes1984** [comment]
@jonathanbossenger why not fork this and put in a pull request?

**Comment by jonathanbossenger** [comment]
I will do, I guess I just wanted to get an idea of interest in the addition...

**Comment by jonathanbossenger** [comment]
Pull request created.

**Comment by jin0x** [comment]
Pert calculator is merged and working on a separate menu.
What do you think about adding another 2 fields which will include the amount of hours and the total amount based on more weight on the pessimistic value. I believe that PERT calculations shouldn't be always the same. For example, some projects are very well defined and they have a very detailed brief where others don't. 
The first paradigm can use a PERT calculation with more weight on the realistic value where the second one which is not so clear can use a PERT calculation with more weight on the pessimistic value. The algorithm is ((optimistic + 2 * likely + 3 * pessimistic) / 6) 
See a screenshot of my alfred app [here](https://www.dropbox.com/s/hpppdxsof989rrl/Screenshot%202017-03-11%2022.39.30.png?dl=0)

What do you think guys?

@vimes1984 tell me if you like the idea in order for me to start implementing it.

**Comment by vimes1984** [comment]
@jin0x Go for it mate! 
Just either use another branch NOT MASTER, or fork it and put in a pull request.

**Comment by jin0x** [comment]
@vimes1984 Used another branch (development) to apply new customisations.
Give it a try and let me know if you like it or not.

**Comment by silicondales** [comment]
My 2 cents on this is its a different "thing" - expertstatsplugin is kind of self explanatory. I'd probably look to make this modular in some way. I'd perhaps include estimation tools as part of a wider package. 

I guess this may also shape our thinking right now, too, so I'd say the PERT (or whatever) estimation tools could form a part of a Codeable plugin which has different modules - or extensions. That way the plugin is kept as light as possible, or at least does what each expert needs / expects it would do.

At this point in the lifecycle, it would probably not be so hard to adopt this approach. In the future, it might be more difficult to "modularize" an already joined-together plugin.

Its a nice idea - and worth expanding upon, but it might be worth thinking about 2 (or more) plugins to house all of this. There are other "modules" which might be nice to add, up to and including client-side "stuff", so I guess what I'm saying is maybe we think about building one backbone at this stage, onto which all those other things might in future be added.

**Comment by 11digitlabs** [comment]
@jin0x tested ok and merged in master. remove calculate button and calculate on blur

**Comment by 11digitlabs** [comment]
@jonathanbossenger thanks!

**Comment by jin0x** [comment]
@11digitlabs I will do it like you suggested and I will let you know

**Comment by vimes1984** [comment]
can this be closed now?
