### ISSUE TITLE
Authentication API endpoint *breaking* change

### ISSUE THREAD

**Issue by drKreso** [codeablehq/expertstatsplugin#42]
Codeable is changing authentication endpoint. Change is simple but it breaks compatibility.

<img width="986" alt="screen shot 2017-03-29 at 10 50 44" src="https://cloud.githubusercontent.com/assets/32063/24463364/ddf84a2c-14a6-11e7-8ad2-122f6f4508da.png">

We are preparing the scene for removal of "auth_token" property from user serializer.

First step that is happening in the next few days is that we are starting to send old "user" object and new "auth_token" string separately. So response will became a hash and not root user object. Then after a while user.auth_token will go away.

We have added the code in our frontend app to handle both cases so there is no downtime in transition, but eventually we will completely turn off auth_code from user and we will kill "old_way" else branch in the fronted receiver.

<img width="994" alt="screen shot 2017-03-29 at 17 42 53" src="https://cloud.githubusercontent.com/assets/32063/24463516/385aeae2-14a7-11e7-90b0-fc2d531342a0.png">

**Comment by 11digitlabs** [comment]
And from where would we take the authToken instead?

**Comment by drKreso** [comment]
Either from response header or directly from response (we send user and auth_token separatel, see  line 18 above)

**Comment by 11digitlabs** [comment]
What about `Then after a while user.auth_token will go away` ? You are saying that it will go away. Are you referring just to the `else` part , old way?

**Comment by drKreso** [comment]
Sorry for confusion. Currently user still contains auth_token. This will be removed from user, but still available via header and additional key (auth_token).
